# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include /home/francis/golang/go/src/Make.inc

TARG=quadtree
GOFILES=\
	defs.go\
	quadtree.go\
	util.go\
	view.go\

include /home/francis/golang/go/src/Make.pkg
