# Copyright 2009 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include /home/francis/golang/go/src/Make.inc

TARG=locserver
GOFILES=\
	messages.go\
	user.go\
	treemanager.go\
	id.go\
	conv.go\

include /home/francis/golang/go/src/Make.pkg
